import "@/styles/globals.css"

import {Inter} from "next/font/google"
import {Analytics} from "@vercel/analytics/react"
import {ThemeProvider} from "@/components/theme-provider"
import {ThemeToggle} from "@/components/theme-toggle"
import Image from "next/image";
import Link from "next/link";
import NavBar from "@/components/NavBar";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans"
})

export const metadata = {
    title: "Coin Stacker",
    description: "Generated by create-t3-app",
    // icons: [{rel: "icon", url: "/favicon.ico"}],
    icons: {
        icon: [
            {
                // media: "(prefers-color-scheme: light)",
                url: "/coinstacker-favicon-16.png",
                href: "/coinstacker-favicon-16.png"
            }
            // {
            //     media: "(prefers-color-scheme: dark)",
            //     url: "/favicon-dark.png",
            //     href: "/favicon-dark.png"
            // }
        ]
    }
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`font-sans ${inter.variable}`}>
        <main id="main">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                <NavBar/>
                {children}
            </ThemeProvider>
            <Analytics/>
        </main>
        </body>
        </html>
    )
}
